#local_backend: true

backend:
  name: github

  repo: meizuflux/portfolio
  base_url: https://cmsauth.meizuflux.com
  use_graphql: true

media_folder: "public/images"
public_folder: "/images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Reading Time", name: "readingTime", widget: "hidden", default: 0}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "created", widget: "datetime"}
      - {label: "Modified Date", name: "modified", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}